spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:postgresql://localhost:5437/booking_db  # МЕНЯЕМ ЗДЕСЬ
    username: booking_login
    password: booking_password

  kafka:
    # ЭТО ТО, ЧТО СОХРАНИТ ТЕБЕ ЧАСЫ ДЕБАГА!
    template:
      observation-enabled: true # Для Producer (отправка в топик)
    listener:
      observation-enabled: true # Для Consumer (чтение из топика)
  jpa:
    hibernate:
      ddl-auto: validate # ТОЛЬКО validate! Flyway создает, Hibernate проверяет.
    show-sql: true
    open-in-view: on
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1

management:
  tracing:
    sampling:
      probability: 1.0 # На dev-окружении пишем 100% трейсов
  zipkin:
    tracing:
      # То же самое для Zipkin (в докере он enterprise_zipkin, локально — localhost)
      endpoint: ${SPRING_ZIPKIN_TRACING_ENDPOINT:http://localhost:9411/api/v2/spans}

server:
  port: 8082