server:
  port: 8082

app:
  payment-service:
    url: http://localhost:8083
  outbox:
    poll-interval-ms: 2000


spring:
  application:
    name: booking-service

  datasource:
    url: jdbc:postgresql://localhost:5437/booking_db
    username: booking_login
    password: booking_password
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

  kafka:
    bootstrap-servers: localhost:9094
    producer:
      acks: all
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          paymentService:
            connect-timeout: 1000
            read-timeout: 2000


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      paymentService:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10        # окно из последних 10 вызовов
        minimum-number-of-calls: 5     # статистику считаем минимум с 5 вызовов
        failure-rate-threshold: 50     # 50% ошибок → breaker РАЗМЫКАЕТСЯ
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true